### ISSUE TITLE
can not build -  File "admin/jscls", line 53, in <module>

### ISSUE THREAD

**Issue by southmeadows** [rsms/fb-mac-messenger#350]
Getting this error on build. The admin jcls is there and executes ok from the command line. 

Traceback (most recent call last):
  File "admin/jscls", line 53, in <module>
    with open(infile) as f:
IOError: [Errno 2] No such file or directory: '/Users/***/Documents/Xcode'
Command /bin/sh failed with exit code 1

**Comment by richardsonsamuel** [comment]
same here

**Comment by sri-0** [comment]
@rsms Do you know what is causing this error? I'm relatively new to Xcode development. I'm having the same issue as this^^

**Comment by rsms** [comment]
Yeah, I think you have a space in your file path. Maybe a folder in ~/Documents which name starts with "Xcode[SPACE]"? The easy fix is to move the project to a place where there are no spaces in the path. Traditionally ~/src is used, but you can place the project anywhere you like.

The trickier fix is to harden up all scripts to handle spaces and submit a PR.

**Comment by rsms** [comment]
I just fixed two obvious paths inside Xcode (3efe35740f58ab0ca6fca20e5ed57d71dd1dd52b). Might not be enough for you, or maybe it was. Try again and see if that fixed it.
